config/routes.rb
Postcoin::Application.routes.draw do
  root 'users#new'

  devise_for :users
  resources :users
  resources :transactions, only: [:new, :create]

  get '/amounts', to: 'pages#amounts', as: :amount_page
end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :user

  validates :user_id, presence: true

  def to_s
    address
  end
end

app/models/concerns/amount_parsable.rb
require 'active_support/concern'

module AmountParsable
  extend ActiveSupport::Concern

  ### Supported Currency Symbols:
  ### Order matters, higher means more priority
  PATTERNS = [
    {
      name: :mBTC_SUFFIX,
      regex: /(\d*.?\d*)\s?mBTC/i,
      satoshify: Proc.new {|num| num.to_millibit_satoshis }
    },
    {
      name: :mBTC_PREFIX,
      regex: /mBTC\s?(\d*.?\d*)/i,
      satoshify: Proc.new {|num| num.to_millibit_satoshis }
    },
    {
      name: :BTC_SUFFIX,
      regex: /(\d*.?\d*)\s?BTC/i,
      satoshify: Proc.new {|num| num.to_satoshis }
    },
    {
      name: :bitcoin_SUFFIX,
      regex: /(\d*.?\d*)\s?bitcoin/i,
      satoshify: Proc.new {|num| num.to_satoshis }
    },
    {
      name: :BTC_SIGN,
      regex: /฿\s?(\d*.?\d*)/i,
      satoshify: Proc.new {|num| num.to_satoshis }
    },
    {
      name: :BTC_PREFIX,
      regex: /BTC\s?(\d*.?\d*)/i,
      satoshify: Proc.new {|num| num.to_satoshis }
    },
    {
      name: :USD,
      regex: /(\d*.?\d*)\s?USD/i,
      satoshify: Proc.new {|num| (num.to_f / Bitstamp.latest).to_satoshis }
    },
    {
      name: :dollar,
      regex: /(\d*.?\d*)\s?dollar/i,
      satoshify: Proc.new {|num| (num.to_f / Bitstamp.latest).to_satoshis }
    },
    {
      name: :USD_SIGN,
      regex: /\$\s?(\d*.?\d*)/i,
      satoshify: Proc.new {|num| (num.to_f / Bitstamp.latest).to_satoshis }
    }
  ]

  def parse(subject)
    PATTERNS.each do |pattern|
      matches = subject.scan(pattern[:regex]).flatten
      matches.each do |match|
        if match.is_number? && satoshis = pattern[:satoshify].call(match)
          return satoshis
        end
      end
    end
    0
  end
end

app/models/email.rb
class Email < ActiveRecord::Base
  include AmountParsable

  belongs_to :recipient, class_name: 'User'
  belongs_to :sender, class_name: 'User'

  after_create :create_transaction

  def create_transaction
    sender      = User.find_by(email: from)
    recipient   = User.find_or_create_by(email: to)
    amount      = parse(subject)
    Transaction.new(
      private_key: Bitcoin::Key.from_base58(sender.private_key),
      sender_address: sender.addresses.last.to_s,
      amount: parse(subject),
      recipient_address: recipient.addresses.last.to_s,
      unspents: fetch_unspents(sender.addresses.last.to_s)
    )
  end

  def fetch_unspents(address)
    url = "http://#{ENV['HELLOBLOCK_ENV']}.helloblock.io/addresses/#{address}/unspents"
    response = HTTParty.get(url)
    response['data']['unspents'].map do |unspent|
      unspent['scriptPubKey'] = [unspent['scriptPubKey']].pack('H*')
      unspent
    end
  end
end

app/models/email_processor.rb
class EmailProcessor < ActiveRecord::Base

  def self.process(email)
    if sender = User.find_by(email: email.from)
      email.to.each do |recipient|
        next if recipient[:email].include?('cc@postco.in')
        receiver = User.find_or_create_by(email: recipient[:email])
        Email.create(
          to: recipient[:email],
          from: email.from,
          subject: email.subject,
          sender_id: sender.id,
          recipient_id: receiver.id
        )
      end
    end
  end
end

app/models/transaction.rb
class Transaction
  include Bitcoin::Builder

  attr_accessor :amount, :unspents, :private_key, :sender_address,
                :recipient_address, :transaction, :total

  FEE = 10_000

  def initialize(private_key:, sender_address:, unspents:, amount:, recipient_address:)
    @amount            = amount
    @unspents          = unspents
    @private_key       = private_key
    @sender_address    = sender_address
    @recipient_address = recipient_address
    transaction_hex    = build_tx{ |transaction| prepare transaction }
    propagate transaction_hex.to_payload.unpack('H*')[0]
  end

  def prepare(transaction)
    @transaction = transaction
    if sufficient_funds?
      unspents.each { |unspent| withdraw unspent } and spend
    else
      raise RuntimeError, 'Insufficient funds.'
    end
  end

  def withdraw(unspent)
    transaction.input do |input|
      input.prev_out(unspent['txHash'], unspent['index'], unspent['scriptPubKey'])
      input.signature_key(private_key)
    end
  end

  def spend
    change = total - (amount + FEE)
    addresses = { recipient_address => amount }
    addresses.merge!({ sender_address => change }) if change > FEE # avoid minimal transactions
    addresses.each{ |address, bitcoin| send(btc: bitcoin, to: address) }
  end

  def send(btc:, to:)
    transaction.output do |o|
      o.value(btc)
      o.script{|s| s.recipient(to) }
    end
  end

  def sufficient_funds?
    @total = unspents.map{|unspent| unspent['value']}.reduce(:+)
    (amount + FEE) <= total
  end

  def propagate(transaction_hex)
    url = "http://#{ENV['HELLOBLOCK_ENV']}.helloblock.io/transactions"
    HTTParty.post(url, body: { rawTxHex: transaction_hex })
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :addresses
  has_many :sent_emails, class_name: 'Email', foreign_key: :sender_id
  has_many :received_emails, class_name: 'Email', foreign_key: :recipient_id

  before_validation :generate_keys, on: :create
  before_validation :generate_password, on: :create, unless: :password
  after_create :generate_address

  validates :private_key, presence: true
  validates :public_key,  presence: true

  def generate_keys
    private_key, self.public_key = Bitcoin.generate_key
    self.private_key = Bitcoin::Key.new(private_key).to_base58
  end

  def generate_address
    addresses.create(address: Bitcoin.pubkey_to_address(public_key))
  end

  def generate_password
    generated_password = Devise.friendly_token.first(8)
    self.password = generated_password
    RegistrationMailer.welcome(email, generated_password).deliver
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :authenticate_user!

  private

  def after_sign_in_path_for(resource)
    request.env['omniauth.origin'] || current_user || root_path
  end

  def fetch_balance(address)
    response = HTTParty.get("http://#{ENV['HELLOBLOCK_ENV']}.helloblock.io/addresses/#{address}")
    response['data']['address']['balance']
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_filter :authenticate_user!, only: :amounts

  def amounts
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_filter :sanitize_params, only: :create

  def new

  end

  def create
    Transaction.new(
      private_key: Bitcoin::Key.from_base58(current_user.private_key),
      sender_address: current_user.addresses.last.to_s,
      unspents: fetch_unspents(current_user.addresses.last.to_s),
      amount: params[:amount].to_i,
      recipient_address: params[:address]
    )
    redirect_to current_user
  end

  private

  def sanitize_params
    balance = fetch_balance(current_user.addresses.last.to_s)
    if params[:address].blank? || params[:amount].blank? ||
      (10_000 + params[:amount].to_i) > balance
      render :new
    end
  end

  def fetch_unspents(address)
    url = "http://#{ENV['HELLOBLOCK_ENV']}.helloblock.io/addresses/#{address}/unspents"
    response = HTTParty.get(url)
    response['data']['unspents'].map do |unspent|
      unspent['scriptPubKey'] = [unspent['scriptPubKey']].pack('H*')
      unspent
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :authenticate_user!, only: :new

  def new

  end

  def show
    @user = current_user
    @balance = fetch_balance(current_user.addresses.last.to_s)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta property="og:url" content="http://www.postco.in">
    <meta property="og:title" content="PostCoin">
    <meta property="og:image" content='http://www.postco.in<%= path_to_image "email.jpg" %>'>

    <title>PostCoin</title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
    <%= javascript_include_tag "application" %>
  </head>

  <body>
    <%= render 'shared/nav_bar' %>
    <%= yield %>
    <div id="fb-root"></div>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-40773883-4', 'postco.in');
      ga('send', 'pageview');
    </script>
  </body>
</html>

app/views/pages/amounts.html.haml
.row
  .small-10.medium-8.small-centered.columns
    %h2.center Sending Money
    %hr
    .small-12.medium-10.small-centered.columns
      %p PostCoin parses subject lines for amount information and understands amounts in the following formats:
      .row
        .small-5.medium-4.columns
          %p.black Millibitcoin
        .small-7.medium-8.columns
          %p 200 mBTC | mBTC 200
      .row
        .small-5.medium-4.columns
          %p.black Bitcoin
        .small-7.medium-8.columns
          %p 200 BTC | BTC 200 | 200 bitcoin | ฿200 | ฿ 200
      .row
        .small-5.medium-4.columns
          %p.black Dollar
        .small-7.medium-8.columns
          %p 200 USD | $200 | $ 200 | 200 dollar | 200 dollars

app/views/shared/_nav_bar.html.haml
%nav
  .row
    .small-12.medium-8.small-centered.columns
      %ul
        %li
          = link_to root_path do
            = render 'shared/email.svg'
        - if user_signed_in?
          %li= link_to 'My Account', current_user
          %li= link_to 'Sign Out', destroy_user_session_path
        - else
          %li= link_to 'Sign Up', new_user_registration_path
          %li= link_to 'Sign In', new_user_session_path

app/views/transactions/new.html.haml
.row
  .small-8.small-centered.columns
    %h2.center WITHDRAW

    = form_tag transactions_path do |f|
      .small-8.small-centered.columns
        = label_tag :address
        = text_field_tag :address
        = label_tag :amount, 'Amount in Satoshis'
        = number_field_tag :amount
        .center
          = submit_tag 'Withdraw', class: 'button'

app/views/users/new.html.haml
.row
  .small-12.small-centered.columns
    %h1.center#title POSTCOIN
  .small-8.small-centered.columns
    %p.center#subtitle Send bitcoin via email
    %hr
    .show-for-small
      .row
        .small-8.small-centered.columns
          = image_tag 'deposit.svg', style: 'height: 100px; width: 100px; display: block; margin: 0 auto;'
          %p.black.center
            Deposit a small amount of bitcoin
      .row
        .small-8.small-centered.columns
          = image_tag 'email.svg',  style: 'height: 100px; width: 100px; display: block; margin: 0 auto;'
          %p.black.center
            Copy us by adding cc@postco.in
      .row
        .small-8.small-centered.columns
          = image_tag 'tag.svg',  style: 'height: 100px; width: 100px; display: block; margin: 0 auto;'
          %p.black.center
            Tag the
            = link_to 'amount', amount_page_path
            in the subject line
    .hide-for-small#section2
      .row
        .small-4.columns
          = image_tag 'deposit.svg', style: 'height: 100px; width: 100px; display: block; margin: 0 auto;'
          %p.black.center
            Deposit a small amount of bitcoin
        .small-4.columns
          = image_tag 'email.svg', style: 'height: 100px; width: 100px; display: block; margin: 0 auto;'
          %p.black.center
            Copy us by adding cc@postco.in
        .small-4.columns
          = image_tag 'tag.svg', style: 'height: 100px; width: 100px; display: block; margin: 0 auto;'
          %p.black.center
            Tag the
            = link_to 'amount', amount_page_path
            in the subject line
    %hr
  .small-8.small-centered.columns#section3
    %h2.center Sample Email
    = image_tag 'emailscreenshot.png'
.row.footer
  .small-8.small-centered.columns
    %p.center
      =link_to 'Facebook', '#', class: 'js-fb-share'
      |
      =link_to 'Twitter', 'https://twitter.com/intent/tweet?original_referer=http%3A%2F%2Fwww.postco.in&text=Tip%20your%20friends%20over%20email%20with%20PostCoin!%20http%3A%2F%2Fwww.postco.in&tw_p=tweetbutton&url=%2F'

app/views/users/show.html.haml
.row
  .small-12.small-centered.columns
    %h2.center MY ACCOUNT
    %h3.center
      = @balance.to_f / 100_000_000
      BTC
    %p.center
      = link_to 'Deposit', '#', id: 'deposit'
      |
      = link_to 'Withdraw', new_transaction_path
    %p#address.center.hidden
      = current_user.addresses.last.to_s
  .small-8.small-centered.columns
    %h3 SENT EMAILS
    - if current_user.sent_emails.any?
      - current_user.sent_emails.each do |email|
        .email
          %p
            = email.to
            %span.right.black
              = email.subject
      %br
      %br
    - else
      %p You have not sent any emails yet.
    %h3 RECEIVED EMAILS
    - if current_user.received_emails.any?
      - current_user.received_emails.each do |email|
        .email
          %p
            = email.from
            %span.right.black
              = email.subject
      %br
      %br
    - else
      %p You have not sent any emails yet.

:coffee
  $('#deposit').on 'click', (e) ->
    e.preventDefault()
    $('#address').removeClass 'hidden'